### ISSUE TITLE
FATAL: Module nvidia_331_uvm not found.

### ISSUE THREAD

**Issue by XiaoshuiHuang** [anuranbaka/OpenDTAM#30]
text_file_name = ./Trajectory_30_seconds/scene_045.txt
Reading: scene_045.png
text_file_name = ./Trajectory_30_seconds/scene_046.txt
Reading: scene_046.png
text_file_name = ./Trajectory_30_seconds/scene_047.txt
Reading: scene_047.png
text_file_name = ./Trajectory_30_seconds/scene_048.txt
Reading: scene_048.png
text_file_name = ./Trajectory_30_seconds/scene_049.txt
Reading: scene_049.png
FATAL: Module nvidia_331_uvm not found.
OpenCV Error: Gpu API call (unknown error) in create, file /home/opendtam/openDTAM/opencv-2.4.9/modules/gpu/src/matrix_operations.cpp, line 255
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/opendtam/openDTAM/opencv-2.4.9/modules/gpu/src/matrix_operations.cpp:255: error: (-217) unknown error in function create

Aborted (core dumped)

The above is the debug. I compile the openDTAM using ubuntu 12.04, cuda 6.0 on Nvidia GTX670 graphic card, opencv 2.4.9.  I have done it for many times. The program can make successfully. However, when I run it using ./a.out, problem occured when it finished read picture 49.

How can I solve it? can you help you?

**Comment by XiaoshuiHuang** [comment]
opendtam@opendtam-Dell-DXP061:~/openDTAM/OpenDTAM-2.4.9_experimental/Cpp/build$ cmake .. -L
-- Found CUDA: /usr/local/cuda (found suitable exact version "6.0")
-- Found CUDA: /usr/local/cuda (found version "6.0")
-- Configuring done
-- Generating done
-- Build files have been written to: /home/opendtam/openDTAM/OpenDTAM-2.4.9_experimental/Cpp/build
-- Cache values
Boost_DIR:PATH=Boost_DIR-NOTFOUND
CMAKE_BUILD_TYPE:STRING=
CMAKE_INSTALL_PREFIX:PATH=/usr/local
CUDA_BUILD_CUBIN:BOOL=OFF
CUDA_BUILD_EMULATION:BOOL=OFF
CUDA_SDK_ROOT_DIR:PATH=CUDA_SDK_ROOT_DIR-NOTFOUND
CUDA_TOOLKIT_ROOT_DIR:PATH=/usr/local/cuda
CUDA_VERBOSE_BUILD:BOOL=OFF
OpenCV_DIR:PATH=/usr/local/share/OpenCV
Qt5Core_DIR:PATH=/usr/lib/x86_64-linux-gnu/cmake/Qt5Core

when I write cmake .. -L, the above information is listed.

**Comment by XiaoshuiHuang** [comment]
I update the Nvidia driver to the newest 352.21, the "Module nvidia_331  not found" error is gone. However, a new problem occurs.

using: 49
using: 50
OpenCV Error: Assertion failed (src1.type() == src2.type()) in scaleAdd, file /home/opendtam/openDTAM/opencv-2.4.9/modules/core/src/matmul.cpp, line 2072
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/opendtam/openDTAM/opencv-2.4.9/modules/core/src/matmul.cpp:2072: error: (-215) src1.type() == src2.type() in function scaleAdd

By the way, after I update the Nvidia driver, I use cmake .., it is no error. When I run make, error occurs

opendtam@opendtam-Dell-DXP061:~/openDTAM/OpenDTAM-2.4.9_experimental/Cpp/build$ make
make[2]: **\* No rule to make target `/usr/lib/libcuda.so', needed by`libOpenDTAM.so'.  Stop.
make[1]: **\* [CMakeFiles/OpenDTAM.dir/all] Error 2
make: **\* [all] Error 2
opendtam@opendtam-Dell-DXP061:~/openDTAM/OpenDTAM-2.4.9_experimental/Cpp/build$ 

Do you know how to fix them?

**Comment by XiaoshuiHuang** [comment]
Hi ,
Finnaly, I make it run correctly. Because of the D0 in the testprog.cpp is alway no value. so it comes the error. I comment these "cout" line, it runs correctly.

In summary, to run correctly of these program. OpenCV compling is the most important step. You need make sure every library OpenCV need. If you compling OpenCV correctly, the program will run.

Thank you.

Xiaoshui

**Comment by anuranbaka** [comment]
Ok, glad it worked. I'm only occaisionally active on this project these days, but I'll try to have a look at things when I get the chance.

**Comment by ginofarisano** [comment]
Hi, I have the same problem. When is read the image 49 show the error:

Reading: scene_048.png
text_file_name = /home/basta/Scrivania/OpenDTAM-2.4.9_experimental/Trajectory_30_seconds/scene_049.txt
Reading: scene_049.png
OpenCV Error: Gpu API call (unknown error) in create, file /home/basta/Scaricati/opencv-2.4.12.3/modules/gpu/src/matrix_operations.cpp, line 255
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/basta/Scaricati/opencv-2.4.12.3/modules/gpu/src/matrix_operations.cpp:255: error: (-217) unknown error in function create

Annullato (core dump creato)

Any solution?

I spend a lot of times to this project,

Gino.

P.S XiaoshuiHuang, if I comment the code when there is the D0 variable the problem is the same.

**Comment by XiaoshuiHuang** [comment]
Hi Gino,
    I guess the problem comes from the OpenCV compling. I think you need to compiling the  OpenCV with CUDA on and compile OpenCV correctly. I can give you the OpenCV compiling script and my testpro.cpp file if you want. Send me a Email and I will give the files to you. 

Xiaoshui

**Comment by ginofarisano** [comment]
Hi Xiaoshui,
thanks for your help, my mail is gino.farisano@gmail.com.
