### ISSUE TITLE
Thread Requested: Graphics 

### ISSUE THREAD

**Issue by LiliMeng** [anuranbaka/OpenDTAM#32]
Hi
After running ./a.out

It encountered:
 Thread Requested: Graphics :  Thread Start: 0x7fea02fe77000xb1cb50:0xb1cb50

Loading
Segmentation fault (core dumped)

Could anyone provide some suggestions? Thanks a lot in advance!:-D

**Comment by XiaoshuiHuang** [comment]
Hi Lili,
    You need to change the code of Testprog.cpp, in order to make sure the loadAhanda function have the meaningful path. I hope it is helpful for you and I hope to hear your next progress.

Regards
Xiaoshui

**Comment by anuranbaka** [comment]
This looks like it's probably right. Tell me if not.

**Comment by cryax** [comment]
sorry I met the same issue, how can I modify loadAhanda?

**Comment by XiaoshuiHuang** [comment]
Hi Cryax,
    You may need to change the first parameter of "loadAhanda" to the available path ( e.g. "../Trajectory_30_seconds/" ).

Best regards
Xiaoshui

**Comment by cryax** [comment]
thanks
