### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by lz199144** [anuranbaka/OpenDTAM#33]
I just installed cuda 7 and opencv 2.4.8 successfully, what's wrong?
lz@lz-pc:~/OpenDTAM/Cpp/build$ make
[  5%] Building CXX object CMakeFiles/OpenDTAM.dir/CostVolume/CostVolume.cpp.o
In file included from /home/lz/OpenDTAM/Cpp/CostVolume/CostVolume.hpp:10:0,
                 from /home/lz/OpenDTAM/Cpp/CostVolume/CostVolume.cpp:6:
/usr/include/opencv2/gpu/gpu.hpp:432:29: error: ‘vector’ does not name a type
 CV_EXPORTS void merge(const vector<GpuMat>& src, GpuMat& dst, Stream& stream = Stream::Null());
                             ^
/usr/include/opencv2/gpu/gpu.hpp:432:35: error: expected ‘,’ or ‘...’ before ‘<’ token
 CV_EXPORTS void merge(const vector<GpuMat>& src, GpuMat& dst, Stream& stream = Stream::Null());
                                   ^
/usr/include/opencv2/gpu/gpu.hpp:438:42: error: ‘vector’ has not been declared
 CV_EXPORTS void split(const GpuMat& src, vector<GpuMat>& dst, Stream& stream = Stream::Null());
                                          ^
/usr/include/opencv2/gpu/gpu.hpp:438:48: error: expected ‘,’ or ‘...’ before ‘<’ token
 CV_EXPORTS void split(const GpuMat& src, vector<GpuMat>& dst, Stream& stream = Stream::Null());
                                                ^
/usr/include/opencv2/gpu/gpu.hpp:1265:4: error: ‘vector’ does not name a type
    vector<Point> locations;
    ^
/usr/include/opencv2/gpu/gpu.hpp:1266:4: error: ‘vector’ does not name a type
    vector<double> confidences;
    ^
/usr/include/opencv2/gpu/gpu.hpp:1267:4: error: ‘vector’ does not name a type
    vector<double> part_scores[4];
    ^
/usr/include/opencv2/gpu/gpu.hpp:1285:31: error: ‘vector’ does not name a type
     void setSVMDetector(const vector<float>& detector);
                               ^
/usr/include/opencv2/gpu/gpu.hpp:1285:37: error: expected ‘,’ or ‘...’ before ‘<’ token
     void setSVMDetector(const vector<float>& detector);
                                     ^
/usr/include/opencv2/gpu/gpu.hpp:1287:12: error: ‘vector’ does not name a type
     static vector<float> getDefaultPeopleDetector();
            ^
/usr/include/opencv2/gpu/gpu.hpp:1288:12: error: ‘vector’ does not name a type
     static vector<float> getPeopleDetector48x96();
            ^
/usr/include/opencv2/gpu/gpu.hpp:1289:12: error: ‘vector’ does not name a type
     static vector<float> getPeopleDetector64x128();
            ^
/usr/include/opencv2/gpu/gpu.hpp:1291:36: error: ‘vector’ has not been declared
     void detect(const GpuMat& img, vector<Point>& found_locations,
                                    ^
/usr/include/opencv2/gpu/gpu.hpp:1291:42: error: expected ‘,’ or ‘...’ before ‘<’ token
     void detect(const GpuMat& img, vector<Point>& found_locations,
                                          ^
/usr/include/opencv2/gpu/gpu.hpp:1295:46: error: ‘vector’ has not been declared
     void detectMultiScale(const GpuMat& img, vector<Rect>& found_locations,
                                              ^
/usr/include/opencv2/gpu/gpu.hpp:1295:52: error: expected ‘,’ or ‘...’ before ‘<’ token
     void detectMultiScale(const GpuMat& img, vector<Rect>& found_locations,
                                                    ^
/usr/include/opencv2/gpu/gpu.hpp:1300:47: error: ‘vector’ has not been declared
     void computeConfidence(const GpuMat& img, vector<Point>& hits, double hit_threshold,
                                               ^
/usr/include/opencv2/gpu/gpu.hpp:1300:53: error: expected ‘,’ or ‘...’ before ‘<’ token
     void computeConfidence(const GpuMat& img, vector<Point>& hits, double hit_threshold,
                                                     ^
/usr/include/opencv2/gpu/gpu.hpp:1303:57: error: ‘vector’ has not been declared
     void computeConfidenceMultiScale(const GpuMat& img, vector<Rect>& found_locations,
                                                         ^
/usr/include/opencv2/gpu/gpu.hpp:1303:63: error: expected ‘,’ or ‘...’ before ‘<’ token
     void computeConfidenceMultiScale(const GpuMat& img, vector<Rect>& found_locations,
                                                               ^
/usr/include/opencv2/gpu/gpu.hpp:1835:5: error: ‘vector’ does not name a type
     vector<GpuMat> prevPyr_;
     ^
/usr/include/opencv2/gpu/gpu.hpp:1836:5: error: ‘vector’ does not name a type
     vector<GpuMat> nextPyr_;
     ^
/usr/include/opencv2/gpu/gpu.hpp:1838:5: error: ‘vector’ does not name a type
     vector<GpuMat> buf_;
     ^
/usr/include/opencv2/gpu/gpu.hpp:1839:5: error: ‘vector’ does not name a type
     vector<GpuMat> unused;
     ^
/home/lz/OpenDTAM/Cpp/CostVolume/CostVolume.cpp: In constructor ‘CostVolume::CostVolume(cv::Mat, FrameID, int, float, float, cv::Mat, cv::Mat, cv::Mat, float, Norm, float, float)’:
/home/lz/OpenDTAM/Cpp/CostVolume/CostVolume.cpp:84:108: error: no matching function for call to ‘cv::Ptr<char>::Ptr(int)’
         R(R),T(T),occlusionThreshold(occlusionThreshold),norm(norm),initialWeight(initialWeight),_cuArray(0) {

**Comment by anuranbaka** [comment]
What was the solution btw? I have never seen this error.

**Comment by lz199144** [comment]
@anuranbaka I solved the problem by rebuilding the opencv.

**Comment by Tariq-Abuhashim** [comment]
Same issue here, didn't compile. I reinstalled OpenCV-3.0.0 with CUDA and GPU switched ON.
Yet, compile was not successful.

In file included from /home/tabuhashim/Dev/OpenDTAM/Cpp/CostVolume/CostVolume.hpp:10:0,
                 from /home/tabuhashim/Dev/OpenDTAM/Cpp/CostVolume/CostVolume.cpp:6:
/usr/local/include/opencv2/gpu/gpu.hpp:432:29: error: ‘vector’ does not name a type
 CV_EXPORTS void merge(const vector<GpuMat>& src, GpuMat& dst, Stream& stream = Stream::Null());
                             ^
/usr/local/include/opencv2/gpu/gpu.hpp:432:35: error: expected ‘,’ or ‘...’ before ‘<’ token
 CV_EXPORTS void merge(const vector<GpuMat>& src, GpuMat& dst, Stream& stream = Stream::Null());
                                   ^
/usr/local/include/opencv2/gpu/gpu.hpp:438:42: error: ‘vector’ has not been declared
 CV_EXPORTS void split(const GpuMat& src, vector<GpuMat>& dst, Stream& stream = Stream::Null());
                                          ^
/usr/local/include/opencv2/gpu/gpu.hpp:438:48: error: expected ‘,’ or ‘...’ before ‘<’ token
 CV_EXPORTS void split(const GpuMat& src, vector<GpuMat>& dst, Stream& stream = Stream::Null());
                                                ^
/usr/local/include/opencv2/gpu/gpu.hpp:1265:4: error: ‘vector’ does not name a type
    vector<Point> locations;
    ^
/usr/local/include/opencv2/gpu/gpu.hpp:1266:4: error: ‘vector’ does not name a type
    vector<double> confidences;
    ^
/usr/local/include/opencv2/gpu/gpu.hpp:1267:4: error: ‘vector’ does not name a type
    vector<double> part_scores[4];
    ^
/usr/local/include/opencv2/gpu/gpu.hpp:1285:31: error: ‘vector’ does not name a type
     void setSVMDetector(const vector<float>& detector);
                               ^
/usr/local/include/opencv2/gpu/gpu.hpp:1285:37: error: expected ‘,’ or ‘...’ before ‘<’ token
     void setSVMDetector(const vector<float>& detector);
                                     ^
/usr/local/include/opencv2/gpu/gpu.hpp:1287:12: error: ‘vector’ does not name a type
     static vector<float> getDefaultPeopleDetector();
            ^
/usr/local/include/opencv2/gpu/gpu.hpp:1288:12: error: ‘vector’ does not name a type
     static vector<float> getPeopleDetector48x96();
            ^
/usr/local/include/opencv2/gpu/gpu.hpp:1289:12: error: ‘vector’ does not name a type
     static vector<float> getPeopleDetector64x128();
            ^
/usr/local/include/opencv2/gpu/gpu.hpp:1291:36: error: ‘vector’ has not been declared
     void detect(const GpuMat& img, vector<Point>& found_locations,
                                    ^
/usr/local/include/opencv2/gpu/gpu.hpp:1291:42: error: expected ‘,’ or ‘...’ before ‘<’ token
     void detect(const GpuMat& img, vector<Point>& found_locations,
                                          ^
/usr/local/include/opencv2/gpu/gpu.hpp:1295:46: error: ‘vector’ has not been declared
     void detectMultiScale(const GpuMat& img, vector<Rect>& found_locations,
                                              ^
/usr/local/include/opencv2/gpu/gpu.hpp:1295:52: error: expected ‘,’ or ‘...’ before ‘<’ token
     void detectMultiScale(const GpuMat& img, vector<Rect>& found_locations,
                                                    ^
/usr/local/include/opencv2/gpu/gpu.hpp:1300:47: error: ‘vector’ has not been declared
     void computeConfidence(const GpuMat& img, vector<Point>& hits, double hit_threshold,
                                               ^
/usr/local/include/opencv2/gpu/gpu.hpp:1300:53: error: expected ‘,’ or ‘...’ before ‘<’ token
     void computeConfidence(const GpuMat& img, vector<Point>& hits, double hit_threshold,
                                                     ^
/usr/local/include/opencv2/gpu/gpu.hpp:1303:57: error: ‘vector’ has not been declared
     void computeConfidenceMultiScale(const GpuMat& img, vector<Rect>& found_locations,
                                                         ^
/usr/local/include/opencv2/gpu/gpu.hpp:1303:63: error: expected ‘,’ or ‘...’ before ‘<’ token
     void computeConfidenceMultiScale(const GpuMat& img, vector<Rect>& found_locations,
                                                               ^
/usr/local/include/opencv2/gpu/gpu.hpp:1835:5: error: ‘vector’ does not name a type
     vector<GpuMat> prevPyr_;
     ^
/usr/local/include/opencv2/gpu/gpu.hpp:1836:5: error: ‘vector’ does not name a type
     vector<GpuMat> nextPyr_;
     ^
/usr/local/include/opencv2/gpu/gpu.hpp:1838:5: error: ‘vector’ does not name a type
     vector<GpuMat> buf_;
     ^
/usr/local/include/opencv2/gpu/gpu.hpp:1839:5: error: ‘vector’ does not name a type
     vector<GpuMat> unused;
     ^
/home/tabuhashim/Dev/OpenDTAM/Cpp/CostVolume/CostVolume.cpp: In constructor ‘CostVolume::CostVolume(cv::Mat, FrameID, int, float, float, cv::Mat, cv::Mat, cv::Mat, float, Norm, float, float)’:
/home/tabuhashim/Dev/OpenDTAM/Cpp/CostVolume/CostVolume.cpp:84:108: error: no matching function for call to ‘cv::Ptr<char>::Ptr(int)’
         R(R),T(T),occlusionThreshold(occlusionThreshold),norm(norm),initialWeight(initialWeight),_cuArray(0) {
                                                                                                            ^
/home/tabuhashim/Dev/OpenDTAM/Cpp/CostVolume/CostVolume.cpp:84:108: note: candidates are:
In file included from /usr/local/include/opencv2/core/base.hpp:55:0,
                 from /usr/local/include/opencv2/core.hpp:54,
                 from /usr/local/include/opencv2/core/core.hpp:48,
                 from /usr/local/include/opencv2/core/gpumat.hpp:48,
                 from /usr/local/include/opencv2/gpu/gpu.hpp:52,
                 from /home/tabuhashim/Dev/OpenDTAM/Cpp/CostVolume/CostVolume.hpp:10,
                 from /home/tabuhashim/Dev/OpenDTAM/Cpp/CostVolume/CostVolume.cpp:6:
/usr/local/include/opencv2/core/cvstd.hpp:344:5: note: template<class Y> cv::Ptr<T>::Ptr(const cv::Ptr<Y>&, T_)
     Ptr(const Ptr<Y>& o, T_ p);
     ^
/usr/local/include/opencv2/core/cvstd.hpp:344:5: note:   template argument deduction/substitution failed:
/home/tabuhashim/Dev/OpenDTAM/Cpp/CostVolume/CostVolume.cpp:84:108: note:   mismatched types ‘const cv::Ptr<T>’ and ‘int’
         R(R),T(T),occlusionThreshold(occlusionThreshold),norm(norm),initialWeight(initialWeight),_cuArray(0) {
                                                                                                            ^
In file included from /usr/local/include/opencv2/core/base.hpp:55:0,
                 from /usr/local/include/opencv2/core.hpp:54,
                 from /usr/local/include/opencv2/core/core.hpp:48,
                 from /usr/local/include/opencv2/core/gpumat.hpp:48,
                 from /usr/local/include/opencv2/gpu/gpu.hpp:52,
                 from /home/tabuhashim/Dev/OpenDTAM/Cpp/CostVolume/CostVolume.hpp:10,
                 from /home/tabuhashim/Dev/OpenDTAM/Cpp/CostVolume/CostVolume.cpp:6:
/usr/local/include/opencv2/core/cvstd.hpp:337:5: note: template<class Y> cv::Ptr<T>::Ptr(const cv::Ptr<Y>&)
     Ptr(const Ptr<Y>& o);
     ^
/usr/local/include/opencv2/core/cvstd.hpp:337:5: note:   template argument deduction/substitution failed:
/home/tabuhashim/Dev/OpenDTAM/Cpp/CostVolume/CostVolume.cpp:84:108: note:   mismatched types ‘const cv::Ptr<T>’ and ‘int’
         R(R),T(T),occlusionThreshold(occlusionThreshold),norm(norm),initialWeight(initialWeight),_cuArray(0) {
                                                                                                            ^
In file included from /usr/local/include/opencv2/core/cvstd.hpp:1057:0,
                 from /usr/local/include/opencv2/core/base.hpp:55,
                 from /usr/local/include/opencv2/core.hpp:54,
                 from /usr/local/include/opencv2/core/core.hpp:48,
                 from /usr/local/include/opencv2/core/gpumat.hpp:48,
                 from /usr/local/include/opencv2/gpu/gpu.hpp:52,
                 from /home/tabuhashim/Dev/OpenDTAM/Cpp/CostVolume/CostVolume.hpp:10,
                 from /home/tabuhashim/Dev/OpenDTAM/Cpp/CostVolume/CostVolume.cpp:6:
/usr/local/include/opencv2/core/ptr.inl.hpp:134:1: note: cv::Ptr<T>::Ptr(const cv::Ptr<T>&) [with T = char]
 Ptr<T>::Ptr(const Ptr& o) : owner(o.owner), stored(o.stored)
 ^
/usr/local/include/opencv2/core/ptr.inl.hpp:134:1: note:   no known conversion for argument 1 from ‘int’ to ‘const cv::Ptr<char>&’
In file included from /usr/local/include/opencv2/core/base.hpp:55:0,
                 from /usr/local/include/opencv2/core.hpp:54,
                 from /usr/local/include/opencv2/core/core.hpp:48,
                 from /usr/local/include/opencv2/core/gpumat.hpp:48,
                 from /usr/local/include/opencv2/gpu/gpu.hpp:52,
                 from /home/tabuhashim/Dev/OpenDTAM/Cpp/CostVolume/CostVolume.hpp:10,
                 from /home/tabuhashim/Dev/OpenDTAM/Cpp/CostVolume/CostVolume.cpp:6:
/usr/local/include/opencv2/core/cvstd.hpp:316:5: note: template<class Y, class D> cv::Ptr<T>::Ptr(Y_, D)
     Ptr(Y_ p, D d);
     ^
/usr/local/include/opencv2/core/cvstd.hpp:316:5: note:   template argument deduction/substitution failed:
/home/tabuhashim/Dev/OpenDTAM/Cpp/CostVolume/CostVolume.cpp:84:108: note:   mismatched types ‘Y_’ and ‘int’
         R(R),T(T),occlusionThreshold(occlusionThreshold),norm(norm),initialWeight(initialWeight),_cuArray(0) {
                                                                                                            ^
In file included from /usr/local/include/opencv2/core/base.hpp:55:0,
                 from /usr/local/include/opencv2/core.hpp:54,
                 from /usr/local/include/opencv2/core/core.hpp:48,
                 from /usr/local/include/opencv2/core/gpumat.hpp:48,
                 from /usr/local/include/opencv2/gpu/gpu.hpp:52,
                 from /home/tabuhashim/Dev/OpenDTAM/Cpp/CostVolume/CostVolume.hpp:10,
                 from /home/tabuhashim/Dev/OpenDTAM/Cpp/CostVolume/CostVolume.cpp:6:
/usr/local/include/opencv2/core/cvstd.hpp:309:5: note: template<class Y> cv::Ptr<T>::Ptr(Y_)
     Ptr(Y\* p);
     ^
/usr/local/include/opencv2/core/cvstd.hpp:309:5: note:   template argument deduction/substitution failed:
/home/tabuhashim/Dev/OpenDTAM/Cpp/CostVolume/CostVolume.cpp:84:108: note:   mismatched types ‘Y_’ and ‘int’
         R(R),T(T),occlusionThreshold(occlusionThreshold),norm(norm),initialWeight(initialWeight),_cuArray(0) {
                                                                                                            ^
In file included from /usr/local/include/opencv2/core/cvstd.hpp:1057:0,
                 from /usr/local/include/opencv2/core/base.hpp:55,
                 from /usr/local/include/opencv2/core.hpp:54,
                 from /usr/local/include/opencv2/core/core.hpp:48,
                 from /usr/local/include/opencv2/core/gpumat.hpp:48,
                 from /usr/local/include/opencv2/gpu/gpu.hpp:52,
                 from /home/tabuhashim/Dev/OpenDTAM/Cpp/CostVolume/CostVolume.hpp:10,
                 from /home/tabuhashim/Dev/OpenDTAM/Cpp/CostVolume/CostVolume.cpp:6:
/usr/local/include/opencv2/core/ptr.inl.hpp:112:1: note: cv::Ptr<T>::Ptr() [with T = char]
 Ptr<T>::Ptr() : owner(NULL), stored(NULL)
 ^
/usr/local/include/opencv2/core/ptr.inl.hpp:112:1: note:   candidate expects 0 arguments, 1 provided
make[2]: *_\* [CMakeFiles/OpenDTAM.dir/CostVolume/CostVolume.cpp.o] Error 1
make[1]: **\* [CMakeFiles/OpenDTAM.dir/all] Error 2
make: **\* [all] Error 2

**Comment by anuranbaka** [comment]
is your std::vector not linking in properly? On my system the standard library is a default include, but you should check on yours

**Comment by Tariq-Abuhashim** [comment]
Hi anuranbaka;

Which OpenCv are you using?  I am using OpenCV-3.0.0
I had to add
using namespace std;
before 
#include "opencv2/gpu/gpu.hpp"
in CostVolume.hpp

However, now I get the following error when running make.

/home/tabuhashim/Dev/OpenDTAM/Cpp/CostVolume/CostVolume.cpp: In constructor ‘CostVolume::CostVolume(cv::Mat, FrameID, int, float, float, cv::Mat, cv::Mat, cv::Mat, float, Norm, float, float)’:
/home/tabuhashim/Dev/OpenDTAM/Cpp/CostVolume/CostVolume.cpp:84:108: error: no matching function for call to ‘cv::Ptr<char>::Ptr(int)’
         R(R),T(T),occlusionThreshold(occlusionThreshold),norm(norm),initialWeight(initialWeight),_cuArray(0) {
                                                                                                            ^
/home/tabuhashim/Dev/OpenDTAM/Cpp/CostVolume/CostVolume.cpp:84:108: note: candidates are:
In file included from /usr/local/include/opencv2/core/base.hpp:55:0,
                 from /usr/local/include/opencv2/core.hpp:54,
                 from /usr/local/include/opencv2/core/core.hpp:48,
                 from /usr/local/include/opencv2/core/gpumat.hpp:48,
                 from /usr/local/include/opencv2/gpu/gpu.hpp:52,
                 from /home/tabuhashim/Dev/OpenDTAM/Cpp/CostVolume/CostVolume.hpp:9,
                 from /home/tabuhashim/Dev/OpenDTAM/Cpp/CostVolume/CostVolume.cpp:6:
/usr/local/include/opencv2/core/cvstd.hpp:344:5: note: template<class Y> cv::Ptr<T>::Ptr(const cv::Ptr<Y>&, T_)
     Ptr(const Ptr<Y>& o, T_ p);
     ^
/usr/local/include/opencv2/core/cvstd.hpp:344:5: note:   template argument deduction/substitution failed:
/home/tabuhashim/Dev/OpenDTAM/Cpp/CostVolume/CostVolume.cpp:84:108: note:   mismatched types ‘const cv::Ptr<T>’ and ‘int’
         R(R),T(T),occlusionThreshold(occlusionThreshold),norm(norm),initialWeight(initialWeight),_cuArray(0) {
                                                                                                            ^
In file included from /usr/local/include/opencv2/core/base.hpp:55:0,
                 from /usr/local/include/opencv2/core.hpp:54,
                 from /usr/local/include/opencv2/core/core.hpp:48,
                 from /usr/local/include/opencv2/core/gpumat.hpp:48,
                 from /usr/local/include/opencv2/gpu/gpu.hpp:52,
                 from /home/tabuhashim/Dev/OpenDTAM/Cpp/CostVolume/CostVolume.hpp:9,
                 from /home/tabuhashim/Dev/OpenDTAM/Cpp/CostVolume/CostVolume.cpp:6:
/usr/local/include/opencv2/core/cvstd.hpp:337:5: note: template<class Y> cv::Ptr<T>::Ptr(const cv::Ptr<Y>&)
     Ptr(const Ptr<Y>& o);
     ^
/usr/local/include/opencv2/core/cvstd.hpp:337:5: note:   template argument deduction/substitution failed:
/home/tabuhashim/Dev/OpenDTAM/Cpp/CostVolume/CostVolume.cpp:84:108: note:   mismatched types ‘const cv::Ptr<T>’ and ‘int’
         R(R),T(T),occlusionThreshold(occlusionThreshold),norm(norm),initialWeight(initialWeight),_cuArray(0) {
                                                                                                            ^
In file included from /usr/local/include/opencv2/core/cvstd.hpp:1057:0,
                 from /usr/local/include/opencv2/core/base.hpp:55,
                 from /usr/local/include/opencv2/core.hpp:54,
                 from /usr/local/include/opencv2/core/core.hpp:48,
                 from /usr/local/include/opencv2/core/gpumat.hpp:48,
                 from /usr/local/include/opencv2/gpu/gpu.hpp:52,
                 from /home/tabuhashim/Dev/OpenDTAM/Cpp/CostVolume/CostVolume.hpp:9,
                 from /home/tabuhashim/Dev/OpenDTAM/Cpp/CostVolume/CostVolume.cpp:6:
/usr/local/include/opencv2/core/ptr.inl.hpp:134:1: note: cv::Ptr<T>::Ptr(const cv::Ptr<T>&) [with T = char]
 Ptr<T>::Ptr(const Ptr& o) : owner(o.owner), stored(o.stored)
 ^
/usr/local/include/opencv2/core/ptr.inl.hpp:134:1: note:   no known conversion for argument 1 from ‘int’ to ‘const cv::Ptr<char>&’
In file included from /usr/local/include/opencv2/core/base.hpp:55:0,
                 from /usr/local/include/opencv2/core.hpp:54,
                 from /usr/local/include/opencv2/core/core.hpp:48,
                 from /usr/local/include/opencv2/core/gpumat.hpp:48,
                 from /usr/local/include/opencv2/gpu/gpu.hpp:52,
                 from /home/tabuhashim/Dev/OpenDTAM/Cpp/CostVolume/CostVolume.hpp:9,
                 from /home/tabuhashim/Dev/OpenDTAM/Cpp/CostVolume/CostVolume.cpp:6:
/usr/local/include/opencv2/core/cvstd.hpp:316:5: note: template<class Y, class D> cv::Ptr<T>::Ptr(Y_, D)
     Ptr(Y_ p, D d);
     ^
/usr/local/include/opencv2/core/cvstd.hpp:316:5: note:   template argument deduction/substitution failed:
/home/tabuhashim/Dev/OpenDTAM/Cpp/CostVolume/CostVolume.cpp:84:108: note:   mismatched types ‘Y_’ and ‘int’
         R(R),T(T),occlusionThreshold(occlusionThreshold),norm(norm),initialWeight(initialWeight),_cuArray(0) {
                                                                                                            ^
In file included from /usr/local/include/opencv2/core/base.hpp:55:0,
                 from /usr/local/include/opencv2/core.hpp:54,
                 from /usr/local/include/opencv2/core/core.hpp:48,
                 from /usr/local/include/opencv2/core/gpumat.hpp:48,
                 from /usr/local/include/opencv2/gpu/gpu.hpp:52,
                 from /home/tabuhashim/Dev/OpenDTAM/Cpp/CostVolume/CostVolume.hpp:9,
                 from /home/tabuhashim/Dev/OpenDTAM/Cpp/CostVolume/CostVolume.cpp:6:
/usr/local/include/opencv2/core/cvstd.hpp:309:5: note: template<class Y> cv::Ptr<T>::Ptr(Y_)
     Ptr(Y\* p);
     ^
/usr/local/include/opencv2/core/cvstd.hpp:309:5: note:   template argument deduction/substitution failed:
/home/tabuhashim/Dev/OpenDTAM/Cpp/CostVolume/CostVolume.cpp:84:108: note:   mismatched types ‘Y_’ and ‘int’
         R(R),T(T),occlusionThreshold(occlusionThreshold),norm(norm),initialWeight(initialWeight),_cuArray(0) {
                                                                                                            ^
In file included from /usr/local/include/opencv2/core/cvstd.hpp:1057:0,
                 from /usr/local/include/opencv2/core/base.hpp:55,
                 from /usr/local/include/opencv2/core.hpp:54,
                 from /usr/local/include/opencv2/core/core.hpp:48,
                 from /usr/local/include/opencv2/core/gpumat.hpp:48,
                 from /usr/local/include/opencv2/gpu/gpu.hpp:52,
                 from /home/tabuhashim/Dev/OpenDTAM/Cpp/CostVolume/CostVolume.hpp:9,
                 from /home/tabuhashim/Dev/OpenDTAM/Cpp/CostVolume/CostVolume.cpp:6:
/usr/local/include/opencv2/core/ptr.inl.hpp:112:1: note: cv::Ptr<T>::Ptr() [with T = char]
 Ptr<T>::Ptr() : owner(NULL), stored(NULL)
 ^
/usr/local/include/opencv2/core/ptr.inl.hpp:112:1: note:   candidate expects 0 arguments, 1 provided
make[2]: *_\* [CMakeFiles/OpenDTAM.dir/CostVolume/CostVolume.cpp.o] Error 1
make[1]: **\* [CMakeFiles/OpenDTAM.dir/all] Error 2
make: **\* [all] Error 2

**Comment by anuranbaka** [comment]
I have side by side installs of 3.0 and 2.4.8 
Different branches use different ones, but I forget which is which off the top of my head. In general if it uses the cuda namespace it is 3 and gpu is 2.4.8 iirc

**Comment by jakexie** [comment]
@lz199144 hello,l have got the same error. please tell me the version of opencv you used?

**Comment by pengwangucla** [comment]
@Tariq-Abuhashim Same issue here, have you solved the problem ? I am building with opencv 3.1.0,  no luck by rebuilding with CUDA.

I fixed it by re-build 249 opencv with CUDA and modify the CMakeList.txt using 249
