### ISSUE TITLE
about reprojection 

### ISSUE THREAD

**Issue by KazukiSakai** [anuranbaka/OpenDTAM#37]
Hi, Paul and all other contributors,

Thank you very much for giving great efforts to implement the DTAM algorithm.
In DTAM paper, they reproject each pixel in keyframe to current frame for updating cost volume. OpenDTAM doesn't follow this idea.
OpenDTAM reprojects current frame to keyframe in in Cpp/CostVolume/utils/reproject.cpp  using cv::warpPerspective().

Why do we reproject current frame to keyframe?
Is our method more accurate or faster?

Thanks.

**Comment by anuranbaka** [comment]
This is wrong. Equation (3) in the paper shows that the frames are projected back into the coordinates of the keyframe. This is the only practical choice, because resampling the cost volume for each frame would be slow and cause artifacts.
