### ISSUE TITLE
about uploading video

### ISSUE THREAD

**Issue by KazukiSakai** [anuranbaka/OpenDTAM#38]
Hi, Paul and all other contributors,

I'd like to confirm that Open DTAM which I downloaded runs correctly.
Would you upload a video about running Open DTAM correctly?
I think it is very convenient for us to confirm that Open DTAM runs correctly.
(If you already uploaded it, would you write a URL where the video was uploaded?)

Thanks.

**Comment by anuranbaka** [comment]
There is no video, it depends on what version you are running and what you are using it for. It is a library, not an application, although there are some demo/test programs in the repos. A video for that is https://drive.google.com/file/d/0B2InjfaONb8dVlRaVlMzaDJKUGc/view?usp=sharing

**Comment by KazukiSakai** [comment]
I'd like to need more information about this video because I want to get high quality results such as the video.

I'd like to ask about the situation when you captured this video.
That is,
* Version : which branch do you used? master?, 2.4.9_experimental? others?
* Parameters:
	* Weighted terms value of regulariser(alpha, beta in DTAM paper Eq.6)
	* Optimization parameters(theta, thetamin, epsilon, and so on.)
	* Number of images which you use for updating cost volume.
	* cost volume near, and far value.(xi_min, xi_max in DTAM figure.1)

Thanks.
