### ISSUE TITLE
make error...

### ISSUE THREAD

**Issue by amiltonwong** [anuranbaka/OpenDTAM#4]
Hi, Paul Foster, 

I had followed the steps according to README.md, but came across the following make error as follows: 
# 

root@milton-desktop:~/OpenDTAM/Cpp/Build# make
[  5%] Building NVCC (Device) object CMakeFiles/OpenDTAM.dir/Optimizer/./OpenDTAM_generated_Optimizer.cu.o
In file included from /root/OpenDTAM/Cpp/Optimizer/Optimizer.cu:4:0:
/root/OpenDTAM/Cpp/Optimizer/Optimizer.cuh:4:41: fatal error: opencv2/gpu/device/common.hpp: No such file or directory
compilation terminated.
CMake Error at OpenDTAM_generated_Optimizer.cu.o.cmake:198 (message):
  Error generating
  /root/OpenDTAM/Cpp/Build/CMakeFiles/OpenDTAM.dir/Optimizer/./OpenDTAM_generated_Optimizer.cu.o

make[2]: **\* [CMakeFiles/OpenDTAM.dir/Optimizer/./OpenDTAM_generated_Optimizer.cu.o] Error 1
make[1]: **\* [CMakeFiles/OpenDTAM.dir/all] Error 2
make: **\* [all] Error 2
# 

It seems the common.hpp in opencv gpu package is missing, but I had installed opencv successfully by : apt-get install libopencv-dev. 
Could you suggest me how to fix this issue?

Best regards,
Milton

**Comment by Nasaah** [comment]
HI!
I am getting the similar error like Milton got.

[  5%] Building NVCC (Device) object CMakeFiles/OpenDTAM.dir/DepthmapDenoiseWeightedHuber/./OpenDTAM_generated_DepthmapDenoiseWeightedHuber.cu.o
nvcc fatal   : Unknown option '-restrict'
CMake Error at OpenDTAM_generated_DepthmapDenoiseWeightedHuber.cu.o.cmake:198 (message):
  Error generating
  /home/****/OpenDTAM/Cpp/CMakeFiles/OpenDTAM.dir/DepthmapDenoiseWeightedHuber/./OpenDTAM_generated_DepthmapDenoiseWeightedHuber.cu.o


make[2]: *** [CMakeFiles/OpenDTAM.dir/DepthmapDenoiseWeightedHuber/./OpenDTAM_generated_DepthmapDenoiseWeightedHuber.cu.o] Error 1
make[1]: *** [CMakeFiles/OpenDTAM.dir/all] Error 2
make: *** [all] Error 2

However,from anuranbakas suggestion I think,I need to make sure that the cuda stuff is being built. and I should use cmake-gui to change those settings.
As both Milton and anuranbaka has solved this problem so can any of you be more specific that how could I make sure that the cuda stuff is being built using cmake gui.
I am using following configuration-
Ubuntu 12.04 32bit
libboost1.48
OpenCV 2.4.9
