### ISSUE TITLE
About make error

### ISSUE THREAD

**Issue by zhouyq041** [anuranbaka/OpenDTAM#40]
Hi paul
    Thank you very much for doing such a nice job.
    However,while dong the final step "make",I faced trobles:

[ 80%] Built target OpenDTAM
Linking CXX executable a.out
libOpenDTAM.so：‘cv::gpu::StreamAccessor::getStream(cv::gpu::Stream const&)’ undefined reference
collect2: error: ld returned 1 exit status
CMakeFiles/a.out.dir/build.make:195: recipe for target 'a.out' failed
make[2]: **\* [a.out] Error 1
CMakeFiles/Makefile2:95: recipe for target 'CMakeFiles/a.out.dir/all' failed
make[1]: **\* [CMakeFiles/a.out.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: **\* [all] Error 2

and my version:open-cv:2.4.9
 the branch i used is :2.4.9 experimental

can you help me?Thank you!

**Comment by anuranbaka** [comment]
That's probably because you didn't build opencv with cuda enabled. rebuild it.

**Comment by RegisWang** [comment]
Please try to follow the issue https://github.com/anuranbaka/OpenDTAM/issues/4#issuecomment-52413493

Install these packages, and rebuild OpenCV

**Comment by zhouyq041** [comment]
It's very thankyou all...
However,after I followed the issue #4 ,I found new problems

/usr/bin/ld: cannot find -lopencv_cudaimgproc
/usr/bin/ld: cannot find -lopencv_cudastereo
collect2: error: ld returned 1 exit status
CMakeFiles/OpenDTAM.dir/build.make:1087: recipe for target 'libOpenDTAM.so' failed
make[2]: **\* [libOpenDTAM.so] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/OpenDTAM.dir/all' failed
make[1]: **\* [CMakeFiles/OpenDTAM.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: **\* [all] Error 2

Did I forget install some other packages?It's very kind of you to tell me..

**Comment by RegisWang** [comment]
Please follow the issue https://github.com/anuranbaka/OpenDTAM/issues/15#issuecomment-54012656
Modify the CMakeLists.txt in line 52
"- - -"
target_link_libraries(OpenDTAM opencv_cudaimgproc opencv_cudastereo)
"+ + +"
target_link_libraries(OpenDTAM opencv_gpu)
You are very close to the result. If you success, could you please reply me here?

**Comment by zhouyq041** [comment]
But there's no "lopencv_cudaimgproc -lopencv_cudastereo" in my OpenDTAM/CPP/CMakeLists.txt.
TT...what should I do.

**Comment by RegisWang** [comment]
稍等一下，我在上课，三点半左右联系

**Comment by zhouyq041** [comment]
hao~

**Comment by RegisWang** [comment]
The branch that I use is 2.4.9_backport, I tried almost every branch, just this work.
The entry is testprog.cpp, that means this file compile to a.out.
But, if you check it in 2.4.9_experimentale, you will find this entry(line 85) isn't for the OpenDTAM-2.4.9_experimental/Trajectory_30_seconds.
That is correct in OpenDTAM-2.4.9_backport/testprog.cpp(line 69-70).

**Comment by zhouyq041** [comment]
OK~Let me try it.Thank you!

**Comment by zhouyq041** [comment]
@RegisWang  Do you have some other contact information like QQ or personal email address?Could you give me one?

**Comment by RegisWang** [comment]
Assume you have a record.

**Comment by zhouyq041** [comment]
Thank you very much!
