### ISSUE TITLE
Implementation about optimization

### ISSUE THREAD

**Issue by KazukiSakai** [anuranbaka/OpenDTAM#41]
Hello.

I'd like to ask about optimizing part. 
1. How do you implement the norm constraint ( norm(q)<1 ) on q? On each pixel, or on each direction for one pixel?
2. How do you implement the one newton step refinement embed in each loop? Is this refinement independent for each pixel?

Thanks.

**Comment by anuranbaka** [comment]
1. The norm constraint is currently on each direction independently, but you could change it to all of them. The original paper had an ambiguity in the spec, so I went with the one that made physical sense to me.
2. The newton step is embedded as a parabola fit at the end of the _a_ value update and independent per pixel. If the mimimum is outside the cost volume, it is clamped to the edge of the volume. This is as in the original paper.
