### ISSUE TITLE
May I ask about how to choose the value of near and far in CostVolume.

### ISSUE THREAD

**Issue by Tsugikuni-Yoriichi** [anuranbaka/OpenDTAM#61]
I have tried with  dataset you give. I can get the pointcloud even it is not very good. The papers says hundreds of photos, I guess it is the reason.

(1)I tried with the images and the pose provided in the txt file.
(2)I tried with a sfm method to calculate the pose of the images provided by you. I can see the depth map.

My problem is that I want to input my own data. I have the poses got the same way as (2). I can see nothing in the result. In your example program, the near and far is set 0.015 and 0. I think there are three values important. layers, near and far.
So how to choose the three values, can you give me some suggestions. In test (2), I first get nothing. After change the value of near, I can see the result just as the test (1).

**Comment by nonlinear1** [comment]
Dou you have this problem?

**Comment by Tsugikuni-Yoriichi** [comment]
Yes, I just think if the initial scale is a problem.
The DTAM should have a pre-set range for the reconstruction. If the range is too far. Resolution for each layer seems not enough.
So layers, near and far parameter for this git project is the most import 3 parameters I think.

**Comment by nonlinear1** [comment]
I have succeeding in output pointcloud. Do you have wechat? maybe we can discuss this issue?

**Comment by Tsugikuni-Yoriichi** [comment]
Sorry for my late reply.
553274016
If it doesn't work, search 15608071319.
